repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
        name: autopep8
- repo: https://github.com/myint/autoflake
  rev: 'v1.4'
  hooks:
    - id: autoflake
      name: autoflake
      language: python
      args: ['--in-place', '--remove-all-unused-imports', --remove-unused-variables]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      name: bandit
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        name: pydocstyle
        additional_dependencies: ["toml"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        name: mypy
        additional_dependencies: [django-stubs==1.12.0, django-stubs-ext==0.5.0, types-pytz==2022.1.1, types-pyyaml==6.0.10, "python-dotenv", "psycopg2"]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        additional_dependencies: ["toml"]
